events {}

http {

    upstream frontend {
        server frontend-service:3000;
    }

    upstream product_service {
        server product-service:8081;
    }

    upstream offer_service {
        server offer-service:8082;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /products {
            proxy_pass http://product_service;
        }

        location /offers {
            proxy_pass http://offer_service;
        }
    }
}