version: "3.9"

services:
  mongo:
    image: iwaseemdevops/db-service:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-service:
    image: iwaseemdevops/product-service:latest
    container_name: product-service
    expose:
      - "8081"
    depends_on:
      mongo:
        condition: service_healthy

  offer-service:
    image: iwaseemdevops/offer-service:latest
    container_name: offer-service
    expose:
      - "8082"
    depends_on:
      mongo:
        condition: service_healthy

  frontend-service:
    image: iwaseemdevops/frontend-service:latest
    container_name: frontend-service
    expose:
      - "3000"
    environment:
      PRODUCT_API: "http://product-service:8081/products"
      OFFER_API: "http://offer-service:8082/offers"
    depends_on:
      - product-service
      - offer-service

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend-service
      - product-service
      - offer-service

volumes:
  mongo-data:
